apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: kanban-auth
spec:
  ports:
  - port: 4001
    targetPort: 5432
  selector:
    name: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: kanban-auth
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: kanban-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      securityContext:
        fsGroup: 101
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: database-data
      - name: tls
        configMap:
          name: database-tls
          defaultMode: 0600
      containers:
      - name: database
        image: docker.io/postgres:latest
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: tls
          mountPath: /var/lib/postgresql/tls
        args: [
          -c, ssl=on,
          -c, ssl_cert_file=/var/lib/postgresql/tls/database.crt,
          -c, ssl_key_file=/var/lib/postgresql/tls/database.key,
        ]
        envFrom:
        - configMapRef:
            name: database
        - secretRef:
            name: database
